# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Minh Nguyen
tagline:
description:      'Full-stack software engineer. Enthusiast of things. These are my ramblings and experiments in tech.'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
